services:
  mongodb:
    image: mongo:7.0
    container_name: myfinanceapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myfinanceapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - myfinanceapp-network

volumes:
  mongodb_data:

networks:
  myfinanceapp-network:
    driver: bridge

